{{- if not .Values.content.url }}
---
apiVersion: v1
kind: Service
metadata:
  name: showroom-content
  namespace: {{- template "showroom-deployer.namespace.name" . }}
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: showroom-content
{{- end }}
