apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-container
    app.kubernetes.io/component: nginx-container
    app.kubernetes.io/instance: nginx-container
  name: nginx-container
  namespace: showroom
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      deployment: nginx-container
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: nginx-container
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/nginx:1.20-ubi8
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
