---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom-terminal
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: terminal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: terminal
    spec:
      # serviceAccountName: .Values.terminal.serviceAccount
      containers:
      - name: terminal
        image: {{ .Values.terminal.image }}
        imagePullPolicy: Always
        args:
          - ttyd
          - -p 8080
          - bash
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
         - containerPort: 8080
           protocol: TCP
        resources:
          {{- toYaml .Values.terminal.resources | nindent 10 }}
