---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-{{ .Values.terminal.serviceAccount }}
  namespace: {{ template "showroom-deployer.namespace.name" . }}
  labels:
    app.kubernetes.io/instance: {{ template "showroom-deployer.namespace.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ .Values.terminal.serviceAccount }}
  namespace: {{ template "showroom-deployer.namespace.name" . }}
