---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: showroom-proxy
  labels:
    app: traefik


spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10
          imagePullPolicy: Always
          args:
            - --api.insecure=true
            - --providers.kubernetesingress=true
            - --api.dashboard=true
            - --api.debug=true
            - --entrypoints.web.address=:8081
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - name: web
              containerPort: 8081
            - name: dashbord
              containerPort: 8080
