  labels:
    - "traefik.enable=true"
    - "traefik.http.services.showroom.loadbalancer.server.port=80"
    - "traefik.http.routers.entrypoints=showroomsecure"
    - "traefik.http.routers.showroom.tls.certresolver=le"
    - "traefik.http.routers.showroom.rule=Host(`{{ showroom_host }}`) && PathPrefix(`/showroom`)"
    - "traefik.http.routers.showroom.middlewares=showroom-stripprefix"
    - "traefik.http.middlewares.showroom-stripprefix.stripprefix.prefixes=/showroom"
