---
# Default values for showroom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

guid: nnnnn

deployer:
  domain: cluster-GUID.GUID.sandboxNUMBERS.opentlc.com

proxy:
  image: docker.io/library/nginx:1.25
  imagePullPolicy: IfNotPresent

content:
  # Only create a content pane, no other tabs will be available
  contentOnly: "false"
  image: ghcr.io/rhpds/showroom-content:latest
  imagePullPolicy: IfNotPresent
  repoUrl: https://github.com/rhpds/showroom_template_default.git
  repoRef: main
  antoraPlaybook: default-site.yml
  antora:
    image: quay.io/rhpds/showroom-content:latest
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi
  user_data: |
    bastion_password: from_helm

terminal:
  setup: "true"
  image: quay.io/rhpds/openshift-showroom-terminal-ocp:latest
  name: terminal
  port: 7681
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  # Set up persistent storage for the lab-user's home directory
  storage:
    setup: "true"
    pvcSize: 5Gi
    # Use default Storage Class when empty
    storageClass: ""

wetty:
  setup: "false"
  image: docker.io/wettyoss/wetty:latest
  name: wetty
  port: 8001
  base: "wetty"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi
  ssh:
    autoSshToBastion: "false"
    sshHost: shared-410-bastion.openshift.redhatworkshops.io
    sshPort: 22
    sshUser: ec2-user
    sshAuth: password
    sshPass: password

# To be fully implemented
codeserver:
  setup: "false"
  image: docker.io/codercom/code-server:latest
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

# To be fully implemented
ocpconsole:
  setup: "false"
