apiVersion: batch/v1
kind: Job
metadata:
  name: showroom-install
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: showroom-helm
        image: quay.io/rhpds/showroom-install:latest
        command: [ "helm" ]
        args:
          - install
          - myshowroom
          - "oci://quay.io/rhpds/showroom"
          - "--repository-cache=/helmwork"
          - "--set deployer.domain=
          - "--set-file content.user_data=/user_data/user_data.yml"
        serviceAccountName: self-provisioner:openshift-config:showroom-deployer
        volumeMounts:
          - name: user-data
            mountPath: /user_data/
          - name: cache
            mountPath: /helmwork
      volumes:
      - name: user-data
        configMap:
          name: showroom-userdata
      - name: cache
        emptyDir: {}
  backoffLimit: 4
# helm install myshowroom oci://quay.io/rhpds/showroom --set deployer.domain=apps.shared-410.openshift.redhatworkshops.io --set-file content.user_data=./azure-user-data.yaml --set general.guid=11021 --namespace showroom-11021-test --create-namespace
