---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showroom
    spec:
      serviceAccountName: {{ .Values.terminal.serviceAccount }}
      containers:

      - name: nginx
        image: {{ .Values.proxy.image }}
        imagePullPolicy: {{ .Values.proxy.imagePullPolicy }}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /data/www
          name: content
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-pid
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: web
          containerPort: 8080

      - name: content
        image: {{ .Values.content.image }}
        imagePullPolicy: {{ .Values.content.imagePullPolicy }}
        env:
        - name: GIT_REPO_URL
          value: {{ .Values.content.repoUrl }}
        - name: GIT_REPO_REF
          value: {{ .Values.content.repoRef }}
        - name: ANTORA_PLAYBOOK
          value: {{ .Values.content.antoraPlaybook }}
        volumeMounts:
        - name: user-data
          mountPath: /user_data/
        - name: showroom
          mountPath: /showroom/
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000

      - name: terminal
        image: {{ .Values.terminal.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GUID
          value: "{{ .Values.guid }}"
        volumeMounts:
        - name: lab-user-home
          mountPath: /home/lab-user
        ports:
        - containerPort: 7681
          protocol: TCP
        resources:
          {{- toYaml .Values.terminal.resources | nindent 10 }}

      volumes:
      - name: showroom
        emptyDir: {}
      - name: user-data
        configMap:
          name: {{ .Values.content.userdataName }}
      - name: content
        configMap:
          name: {{ .Values.proxy.indexHtmlConfigMap }}
      - name: nginx-config
        configMap:
          defaultMode: 420
          name: {{ .Values.proxy.nginxConfigMap }}
      - name: nginx-pid
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: lab-user-home
{{- if .Values.terminal.storage.setup }}
        persistentVolumeClaim:
          claimName: lab-user-home
{{- else }}
        emptyDir: {}
{{- end }}
