{{- if .Values.storage.setup }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-user-home
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.terminal.storage.storageClass }}
  storageClassName: {{ .Values.terminal.storage.storageClass }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.terminal.storage.pvcSize }}
{{- end }}
