---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
    #namespace: {{- template "namespace.name" . }}
  namespace: {{- template "namespace.name" . }}
  labels:
    app.kubernetes.io/name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      serviceAccountName: traefik
        #serviceAccountName: {{ .Values.traefik.serviceAccount }}
      containers:
      - name: traefik
        image: traefik:2.9
        # image: {{ .Values.traefik.image }}
        imagePullPolicy: Always
        args:
          - --api.insecure
          - --providers.kubernetesingress
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: web
          containerPort: 80
        - name: dashboard
          containerPort: 8080
            #        securityContext:
            #          allowPrivilegeEscalation: true
            #          capabilities:
            #            drop: ["ALL"]
            #      securityContext:
            #        runAsNonRoot: false
            #        seccompProfile:
            #          type: RuntimeDefault
