apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  selector:
    app.kubernetes.io/name: showroom
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  selector:
    app.kubernetes.io/name: showroom
  type: ClusterIP
  ports:
    - targetPort: web
      port: 80
