---
# Default values for showroom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# when launched as cluster-admin, chart can create namespaces
# when launched as showroom-deployer user, chart CANNOT create namespaces

namespace:
  create: true
  name: showroom

guid: nnnn

deployer:
  domain: cluster-GUID.GUID.sandboxNUMBERS.opentlc.com

proxy:
  image: quay.io/rhpds/showroom-nginx:latest

home:
  image: registry.redhat.io/ubi8/httpd-24:latest
  contentMount: /var/www/html/
  contentConfig: showroom-html
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi

#
# Use this to reference an external url for the documentation.
#
# documentation:
#   url: https://my-documentation.external.com

#
# Ignored if using {"documentation":{"url":"..."}}
#
content:
  image: ghcr.io/rhpds/showroom-content:latest
  repoUrl: https://github.com/rhpds/showroom_default_template.git
  repoRef: main
  antoraPlaybook: default-site.yml
  userdataName: showroom-userdata
  antora:
    image: quay.io/rhpds/showroom-content:latest
    # image: docker.io/antora/antora:latest
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi
  user_data: |
    bastion_password: from_helm

#
# Remove it to hide.
#
terminal:
  image: ghcr.io/rhpds/showroom-terminal:latest
  name: terminal
  serviceAccount: showroom-terminal
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

# Remove it to hide.
#
# codeserver:
#   image: docker.io/codercom/code-server:latest
#   resources:
#     limits:
#       memory: 512Mi
#     requests:
#       cpu: 500m
#       memory: 512Mi

#
# Services to be shown as tabs on the right panel.
#
services:
  - name: codeserver
    url: https://codeserver-codeserver.apps.cluster-guid.sandbox.opentlc.com
  # - name: myservice
  #   url: http://myservice.com/hello2
