---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $bytes := .Files.Glob "files/*" }}
{{-   $subdir := dir $path }}
{{-   $safeSubdir := default "" $subdir }}
{{-   $currentFilename := ($path | replace (printf "%s/" $safeSubdir) "" ) }}
{{   $currentFilename | indent 2 }}: |
{{   tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}
